channels:
- bioconda
- conda-forge
- defaults
dependencies:
- bioconductor-edger==3.24.3
- r-amap==0.8_16
- r-dplyr==0.8.5
- r-gdata==2.18.0
- r-ggplot2==3.3.0
- r-gplots==3.0.3
- r-gridextra==2.3
- bioconductor-limma==3.38.3
- r-rcolorbrewer==1.1_2
- r-reshape2==1.4.4
- r-reshape==0.8.8
- r-scales==1.1.0
- r-survival==3.1_12
- r-tidyr==1.0.2
- r-tidyverse=1.3.0
- r-plotly
- r-jsonlite
- r-rcurl
- r-ggdendro
- r-ggrepel
name: legacy-default
